name: Docker Image CI

on: [push]

jobs:
  lint:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3.5.1
      - name: Run hadolint
        run: make lint
  build:
    needs: lint
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3.5.1
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag phantomjs-ruby:$(date +%s)
