name: Docker Image CI

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - name: Run hadolint
        run: make lint
  build:
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag phantomjs-ruby:$(date +%s)
