name: Docker Image CI

on: [push]

jobs:
  lint:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4.2.0
      - name: Run hadolint
        run: make lint
  build:
    needs: lint
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4.2.0
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag phantomjs-ruby:$(date +%s)
